### ISSUE TITLE
GIS Data dictionary for Oregon Fire

### ISSUE THREAD

**Issue by steveleathers** [Caged/maptime#2]
http://www.oregon.gov/odf/gis/pdf/historicfires.pdf

**Comment by caged** [comment]
Thanks for the link, @steveleathers!  I added it to the readme.  I'm curious to know where you found this at?  I wasn't able to find it googling around for a bit.

**Comment by steveleathers** [comment]
Strangely enough, I found it by following your possible metadata lead (http://www.oregon.gov/ODF/Pages/index.aspx) and searching the page for "NFCA", since I noticed there were ~9000 records with that description. It was the 4th result returned. Good thing my reading comprehension skills are terrible and I didn't notice the explanation that's right below the link in the script!
